---
- import_playbook: common.yml

- name: Configurar servidor de aplicação
  hosts: app
  become: true
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Copiar página web
      copy:
        src: ../files/index.html
        dest: /var/www/html/index.html

    - name: Instalar autofs
      apt:
        name: autofs
        state: present

    - name: Criar diretório base para montagem NFS
      file:
        path: /var/nfs
        state: directory
        mode: '0755'

    - name: Configurar auto.master para autofs
      copy:
        content: |
          /var/nfs /etc/auto.nfs --timeout=60
        dest: /etc/auto.master

    - name: Configurar auto.nfs para montagem automática
      copy:
        content: |
          * -fstype=nfs4,rw,soft,intr arq.lucas.jaaziel.devops:/dados/nfs/&
        dest: /etc/auto.nfs

    - name: Habilitar e reiniciar autofs
      systemd:
        name: autofs
        enabled: yes
        state: restarted
