---
- import_playbook: common.yml

- name: Configurar servidor de arquivos
  hosts: arq
  become: true
  tasks:
    # Configuração DHCP
    - name: Instalar ISC DHCP Server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Configurar dhcpd.conf
      copy:
        content: |
          option domain-name "lucas.jaaziel.devops";
          option domain-name-servers 1.1.1.1, 8.8.8.8;
          default-lease-time 600;
          max-lease-time 7200;
          ddns-update-style none;
          authoritative;
          subnet 192.168.56.0 netmask 255.255.255.0 {
            range 192.168.56.50 192.168.56.100;
            option routers 192.168.56.1;
            host db { hardware ethernet 08:00:27:11:11:11; fixed-address 192.168.56.115; }
            host app { hardware ethernet 08:00:27:22:22:22; fixed-address 192.168.56.155; }            
          }
        dest: /etc/dhcp/dhcpd.conf
      notify: restart dhcp

    - name: Habilitar interface DHCP
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="eth1"'
      notify: restart dhcp

    # Configuração LVM com comandos diretos
    - name: Instalar LVM2
      apt:
        name: lvm2
        state: present

    - name: Criar volumes físicos
      command: "pvcreate /dev/{{ item }}"
      loop:
        - sdb
        - sdc
        - sdd

    - name: Criar volume group
      command: vgcreate dados /dev/sdb /dev/sdc /dev/sdd

    - name: Criar logical volume
      command: lvcreate -n ifpb -L 15g dados

    - name: Formatar LV como ext4
      filesystem:
        fstype: ext4
        dev: /dev/dados/ifpb

    - name: Criar diretório de montagem
      file:
        path: /dados
        state: directory

    - name: Montar partição
      mount:
        path: /dados
        src: /dev/dados/ifpb
        fstype: ext4
        state: mounted
    # Configuração NFS
    - name: Instalar NFS Server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Criar usuário nfs-ifpb (sem shell para segurança)
      user:
        name: nfs-ifpb
        shell: /usr/sbin/nologin
        system: yes
        state: present
        create_home: no

    - name: Obter UID e GID do usuário nfs-ifpb
      command: id -u nfs-ifpb
      register: nfs_ifpb_uid

    - name: Obter GID do usuário nfs-ifpb
      command: id -g nfs-ifpb
      register: nfs_ifpb_gid

    - name: Criar diretório compartilhado NFS
      file:
        path: /dados/nfs
        state: directory
        owner: nfs-ifpb
        group: nfs-ifpb
        mode: '0755'

    - name: Configurar exportações NFS
      lineinfile:
        path: /etc/exports
        line: "/dados/nfs 192.168.56.0/24(rw,sync,no_subtree_check,all_squash,anonuid={{ nfs_ifpb_uid.stdout }},anongid={{ nfs_ifpb_gid.stdout }})"
        create: true
        state: present
        regexp: '^/dados/nfs'

    - name: Exportar compartilhamentos NFS
      command: exportfs -ra

    - name: Habilitar e iniciar serviço NFS
      systemd:
        name: nfs-kernel-server
        enabled: yes
        state: started

    - name: Habilitar e iniciar serviço rpcbind
      systemd:
        name: rpcbind
        enabled: yes
        state: started

  handlers: # <-- Nova seção para handlers
    - name: restart dhcp
      ansible.builtin.service:
        name: isc-dhcp-server
        state: restarted

