---
- import_playbook: common.yml

- name: Configurar servidor de banco de dados
  hosts: db
  become: true
  tasks:
    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Instalar autofs
      apt:
        name: autofs
        state: present

    - name: Criar diretório base para montagem NFS
      file:
        path: /var/nfs
        state: directory
        mode: '0755'

    - name: Configurar auto.master para montagem direta
      copy:
        content: |
          /- /etc/auto.nfs
        dest: /etc/auto.master
        owner: root
        group: root
        mode: '0644'

    - name: Configurar auto.nfs para o compartilhamento /dados/nfs
      copy:
        content: |
          /var/nfs arq.lucas.jaaziel.devops:/dados/nfs -fstype=nfs4,rw,soft,intr
        dest: /etc/auto.nfs
        owner: root
        group: root
        mode: '0644'

    - name: Habilitar e reiniciar autofs
      systemd:
        name: autofs
        enabled: yes
        state: restarted

    - name: Garantir que o serviço rpcbind esteja ativo (necessário para NFS)
      systemd:
        name: rpcbind
        enabled: yes
        state: started
