---
- import_playbook: common.yml

- name: Configurar servidor de banco de dados
  hosts: db
  become: true
  tasks:
    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Instalar autofs
      apt:
        name: autofs
        state: present

    - name: Configurar autofs
      copy:
        content: |
          /nfs /etc/auto.nfs
        dest: /etc/auto.master

    - name: Configurar ponto de montagem
      copy:
        content: |
          * -fstype=nfs4 arq.lucas.jaaziel.devops:/dados/nfs/&
        dest: /etc/auto.nfs

    - name: Reiniciar autofs
      service:
        name: autofs
        state: restarted
